version: "3.0"
services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db:/app/db # Persist the SQLite database
    expose:
      - "8000" # Internal port to expose the backend service to other containers
    networks:
      - app_network
    restart: always # Restart policy for production stability

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://blogspotapi.mine.bz/"
    volumes:
      - dist:/app/dist # Persist the frontend build
    networks:
      - app_network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - dist:/srv
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db: # Named volume for the SQLite database
  dist: # Named volume for the frontend build
  caddy_data:
  caddy_config:
