name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/blogspot
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker image prune -f
            docker container prune -f

# run these manually on server
# docker-compose exec backend python manage.py makemigrations
# docker-compose exec backend python manage.py migrate
