name: Deploy to VPS

on:
  push:
    branches:
      - main # Adjust if you're using a different branch
  pull_request:
    branches:
      - main # Adjust if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Add SSH key for secure connection
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.VPS_HOST }}

      # Step 3: SSH into the VPS and deploy the latest code
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} -p ${{ secrets.VPS_PORT }} "
            cd ~/blogspot &&
            git pull origin main &&
            docker-compose down &&
            docker-compose up -d --build &&
            docker-compose exec backend python manage.py makemigrations &&
            docker-compose exec backend python manage.py migrate
          "
